### ISSUE TITLE
Getting CondaVerificationError error

### ISSUE THREAD

**Issue by amrit3701** [realthunder/FreeCADMakeImage#3]
The script run about ~1 hr and from console output it looks like FreeCAD is successfully compiled (both build and install target) but in **Package  Plan** section the script fails with given below error.
 
```
CondaVerificationError: The package for qt located at /Users/ambu/miniconda3/pkgs/qt-5.12.5-h514805e_3
appears to be corrupted. The path 'lib/libQt5WebEngineCore.5.12.5.dylib'
specified in the package manifest cannot be found.
```

**Console Logs:** https://paste.ubuntu.com/p/nyMFYkvMjP/

Please help me how to fix this error.

**Comment by realthunder** [comment]
I don't know what's wrong. It seems that MacOS qt package is corrupted? You can try to install with a different version and see. Change [this](https://github.com/realthunder/FreeCADMakeImage/blob/6f4a5ae181c5facce5cd817f6baad09b879fd756/conda/install.sh#L13) line to 
```
qt=5.12.1 \
```

**Comment by amrit3701** [comment]
> I don't know what's wrong. It seems that MacOS qt package is corrupted? You can try to install with a different version and see. Change [this](https://github.com/realthunder/FreeCADMakeImage/blob/6f4a5ae181c5facce5cd817f6baad09b879fd756/conda/install.sh#L13) line to
> 
> ```
> qt=5.12.1 \
> ```

Hi @realthunder ,

After changing the qt version to `qt=5.9.7` solved the problem. Now, I am getting below error:

```bash
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - freecad-asm3

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/freecad/label/dev/osx-64
  - https://conda.anaconda.org/freecad/label/dev/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://conda.anaconda.org/freecad/osx-64
  - https://conda.anaconda.org/freecad/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

For more detail: https://paste.ubuntu.com/p/xQ3j4Ys9kR/

**Comment by amrit3701** [comment]
@realthunder Looks like `conda` failed to locate local `freecad-asm3` package.
https://github.com/realthunder/FreeCADMakeImage/blob/master/conda/install.sh#L21

**Comment by amrit3701** [comment]
@realthunder 

```bash
λ ~/Documents/FreeCADMakeImage/build/conda/img/recipes/ master* ls
AppDir                                        MacBundle                                     install.sh
FreeCAD-img-OSX-Conda-Py3-Qt5-20200501-x86_64 freecad_asm3                                  setup.sh
Info.plist.template                           get_freecad_version.py                        solvespace
λ ~/Documents/FreeCADMakeImage/build/conda/img/recipes/ master* conda install -p FreeCAD-img-OSX-Conda-Py3-Qt5-20200501-x86_64/FreeCAD.app/Contents/Resources --verbose --use-local freecad-asm3 -y
Collecting package metadata (current_repodata.json): ...working... Unable to retrieve repodata (response: 404) for https://conda.anaconda.org/freecad/osx-64/current_repodata.json

Unable to retrieve repodata (response: 404) for https://conda.anaconda.org/freecad/label/dev/osx-64/current_repodata.json

done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): ...working... Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='conda.anaconda.org', port=443): Read timed out. (read timeout=9.15)")': /freecad/noarch/repodata.json

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='conda.anaconda.org', port=443): Read timed out. (read timeout=9.15)")': /freecad/osx-64/repodata.json

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /conda-forge/osx-64/repodata.json

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /freecad/label/dev/noarch/repodata.json

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /pkgs/main/noarch/repodata.json

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /pkgs/r/noarch/repodata.json

Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: SysCallError(54, 'ECONNRESET')"))': /pkgs/r/noarch/repodata.json

Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError("bad handshake: SysCallError(54, 'ECONNRESET')"))': /pkgs/main/noarch/repodata.json

done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Traceback (most recent call last):
  File "/Users/ambu/miniconda3/lib/python3.7/site-packages/conda/cli/install.py", line 265, in install
    should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
  File "/Users/ambu/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
    should_retry_solve)
  File "/Users/ambu/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
    force_remove, should_retry_solve)
  File "/Users/ambu/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 275, in solve_final_state
    ssc = self._add_specs(ssc)
  File "/Users/ambu/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 555, in _add_specs
    explicit_pool = ssc.r._get_package_pool(self.specs_to_add)
  File "/Users/ambu/miniconda3/lib/python3.7/site-packages/conda/resolve.py", line 553, in _get_package_pool
    pool = self.get_reduced_index(specs)
  File "/Users/ambu/miniconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/Users/ambu/miniconda3/lib/python3.7/site-packages/conda/resolve.py", line 574, in get_reduced_index
    explicit_specs, features = self.verify_specs(explicit_specs)
  File "/Users/ambu/miniconda3/lib/python3.7/site-packages/conda/resolve.py", line 288, in verify_specs
    raise ResolvePackageNotFound(bad_deps)
conda.exceptions.ResolvePackageNotFound:
  - freecad-asm3

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ambu/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
    return func(*args, **kwargs)
  File "/Users/ambu/miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "/Users/ambu/miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
    return getattr(module, func_name)(args, parser)
  File "/Users/ambu/miniconda3/lib/python3.7/site-packages/conda/cli/main_install.py", line 20, in execute
    install(args, parser, 'install')
  File "/Users/ambu/miniconda3/lib/python3.7/site-packages/conda/cli/install.py", line 286, in install
    raise PackagesNotFoundError(e._formatted_chains, channels_urls)
conda.exceptions.PackagesNotFoundError: The following packages are not available from current channels:

  - freecad-asm3

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/freecad/label/dev/osx-64
  - https://conda.anaconda.org/freecad/label/dev/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://conda.anaconda.org/freecad/osx-64
  - https://conda.anaconda.org/freecad/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


λ ~/Documents/FreeCADMakeImage/build/conda/img/recipes/ master*
```

When I trigger `conda install -p FreeCAD-img-OSX-Conda-Py3-Qt5-20200501-x86_64/FreeCAD.app/Contents/Resources --verbose --use-local solvespace -y` condo found solvespace package from current directory and install it.

Do you know what's going on here? I am unable to found the issue. :(

**Comment by realthunder** [comment]
Have you tried with `qt=5.12.1`? I suggested this version because, you are likely compiled freecad with Qt 5.12.X (either 1 or 5), which should be binary compatible, but not 5.9. So if you try to install a 5.12.X compiled freecad into a conda environment with Qt 5.12.1, it won't work.

My own release force compile using 5.12.1, because there is a known stylesheet related bug in Qt 5.12.5 which is the latest conda release.

My suggestion is you try install with qt=5.12.1 first, if you haven't tried it. If that won't work, try recompile freecad with explicit qt version. To do that, delete freecad_asm3_XXX directory in `FreeCADMakeImage/build/conda/asm3/env/conda-bld/`. Then change [this](https://github.com/realthunder/FreeCADMakeImage/blob/master/conda/freecad_asm3/meta.yaml#L35) and [this](https://github.com/realthunder/FreeCADMakeImage/blob/6f4a5ae181c5facce5cd817f6baad09b879fd756/conda/freecad_asm3/meta.yaml#L59) lines to `- qt 5.12.1`. If you want 5.9.7, then you should change the three lines accordingly.

Speaking from my own experience, when doing the latest release, I encountered lots of dependency error when conda solves the environment. It must have been messed up somehow, so I just deleted the whole conda environment at `FreeCADMakeImage/build/conda/asm3/env` and try again, and everything worked just fine.

**Comment by amrit3701** [comment]
@realthunder 

Things which I did:

1. Removed `build` folder.
1. Changed [this line](https://github.com/realthunder/FreeCADMakeImage/blob/master/conda/install.sh#L13) with `qt=5.12.1 \`, [this line](https://github.com/realthunder/FreeCADMakeImage/blob/master/conda/freecad_asm3/meta.yaml#L35) with `- qt 5.12.1` and last [this line](https://github.com/realthunder/FreeCADMakeImage/blob/master/conda/freecad_asm3/meta.yaml#L59) with `- qt 5.12.1`.
1. Run, `./mkimg.sh conda sudo` command.
1. Compilation and Installtion is successful but still failing on install `freecad-asm3` from local.

Full Logs: https://drive.google.com/file/d/1kt_4YhX-J-qS1SMvrG8drhqu2rx3sGtd/view?usp=sharing

In the logs, some line start with `ML:`. Please skip that lines. I just did for debugging purposes.

To be honest, now all this stuff afraid me. Can we copy dependencies `freecad-asm3` manually without using condo to make it work? Do I try it on the Linux system? Can I create `*.dmg` package on Linux OS?

**Comment by realthunder** [comment]
> To be honest, now all this stuff afraid me. Can we copy dependencies `freecad-asm3` manually without using condo to make it work? Do I try it on the Linux system? Can I create `*.dmg` package on Linux OS?

I don't think it is possible to do on Linux. 

I searched around, and found [this](https://github.com/conda/conda/issues/7024) issue which seems like what you have right now. Have you installed any other miniconda instance somewhere? If so, please remove it and try again. As you are failing on the last step, you can retry only this step with

`./mkimg.sh conda sudo package`

BTW, on MacOSX, there is no need to use `sudo`. But since you have used it, you'll have to keep using it. `sudo` is necessary on Linux, because conda is run through `docker` there.

**Comment by realthunder** [comment]
The more specific comment I referring with that issue is [this](https://github.com/conda/conda/issues/7024#issuecomment-507298753).

**Comment by amrit3701** [comment]
> I don't think it is possible to do on Linux.
> 
> I searched around, and found [this](https://github.com/conda/conda/issues/7024) issue which seems like what you have right now. Have you installed any other miniconda instance somewhere? If so, please remove it and try again. As you are failing on the last step, you can retry only this step with
> 
> `./mkimg.sh conda sudo package`
> 
> BTW, on MacOSX, there is no need to use `sudo`. But since you have used it, you'll have to keep using it. `sudo` is necessary on Linux, because conda is run through `docker` there.

It only failed to install `freecad-asm3` package. When I try to install `solvespace` with --use-local flag, it succeeds. So I think here I have some other problem. But just for confirmation, now I am going to completely remove condo, and all condo envs `/home/user/minicode3`. Then run `./mkimg.sh` with new condo and let you know.

BTW, Is some CI upload the latest release of FreeCAD at https://github.com/FreeCAD/FreeCAD/releases or you do it manually each week?

**Comment by realthunder** [comment]
> BTW, Is some CI upload the latest release of FreeCAD at https://github.com/FreeCAD/FreeCAD/releases or you do it manually each week?

I am not in charge of FreeCAD release. I do my owner release at [here](https://github.com/realthunder/FreeCAD_assembly3/releases). And yes, I do it manually with the scripts in this repo.
